name: Push to CapRover example
env:
  DockerContainer: 'template'
on:
  workflow_dispatch: 
    
jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
    # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.DockerContainer}}:latest
          secrets: |
            "secret_user=${{ secrets.DB_USER }}"
            "secret_password=${{ secrets.DB_PASSWORD }}"
            "secret_server=${{ secrets.DB_SERVER }}"
            "secret_database=${{ secrets.DB_DATABASE }}"

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image:  ${{ secrets.DOCKERHUB_USERNAME }}/${{env.DockerContainer}}:latest
